from app_config import *

EVENT_QUIT = QUIT
EVENT_PREV_MONITOR = PREV_MONITOR
EVENT_NEXT_MONITOR = NEXT_MONITOR
EVENT_SHUTDOWN_PROMPT = SHUTDOWN_PROMPT
EVENT_SHUTDOWN = SHUTDOWN
EVENT_OPEN_GROUP_VIEW = OPEN_GROUP_VIEW
EVENT_OPEN_MONITOR_LIST_VIEW = 'open_monitor_list_view'

EVENT_MOUSE_CLICK = 'mouse_click'
EVENT_MOUSE_DRAG = 'mouse_drag'

INTERNAL_EVENT_RELEASE_COMPONENT = 'release_component'
INTERNAL_EVENT_HIDE_MOUSE = 'hide_mouse'
INTERNAL_EVENT_SHOW_MOUSE = 'show_mouse'


def get_event_type_configs():
    return [EVENT_QUIT, EVENT_PREV_MONITOR, EVENT_NEXT_MONITOR, EVENT_SHUTDOWN, EVENT_OPEN_GROUP_VIEW, EVENT_SHUTDOWN_PROMPT]