from common_lables import *

EVENT_QUIT = QUIT
EVENT_PREV_MONITOR = PREV_MONITOR
EVENT_NEXT_MONITOR = NEXT_MONITOR
EVENT_SHUTDOWN_PROMPT = SHUTDOWN_PROMPT
EVENT_SHUTDOWN = SHUTDOWN
EVENT_OPEN_GROUP_VIEW = OPEN_GROUP_VIEW
EVENT_OPEN_MONITOR_LIST_VIEW = 'open_monitor_list_view'
EVENT_OPEN_MENU = OPEN_MENU

EVENT_MOUSE_CLICK = 'mouse_click'
EVENT_MOUSE_DOWN = 'mouse_down'
EVENT_MOUSE_DRAG = 'mouse_drag'
EVENT_MOUSE_UP = 'mouse_up'

INTERNAL_EVENT_COMPONENT_SWITCHED = 'component_switched'
INTERNAL_EVENT_RELEASE_COMPONENT = 'release_component'
INTERNAL_EVENT_HIDE_MOUSE = 'hide_mouse'
INTERNAL_EVENT_SHOW_MOUSE = 'show_mouse'
INTERNAL_EVENT_LAUNCH_TASK = 'launch_task'

INTERNAL_EVENT_SWITCH_TO_MONITOR_STREAM = "switch_to_monitor_stream"
INTERNAL_EVENT_NEW_STREAM_FRAME = 'new_stream_frame'
INTERNAL_EVENT_STREAM_ERROR_RETRYING = "stream_error_retrying"

INTERNAL_EVENT_NEXT_PATROL_MONITOR = 'next_patrol_monitor'
INTERNAL_EVENT_MONITOR_GROUPS_DATA_LOAD = 'monitor_groups_data_load'
INTERNAL_EVENT_MONITOR_GROUPS_DATA_LOAD_ERROR = 'monitor_groups_data_load_error'

CONFIG_EVENT_TYPES = (EVENT_QUIT, EVENT_PREV_MONITOR, EVENT_NEXT_MONITOR, EVENT_SHUTDOWN, EVENT_OPEN_GROUP_VIEW,
                      EVENT_SHUTDOWN_PROMPT, EVENT_OPEN_MENU)

QUIT_APP_EVENTS = [EVENT_QUIT, EVENT_SHUTDOWN]
