import app_config

EVENT_QUIT = app_config.QUIT
EVENT_PREV_MONITOR = app_config.PREV_MONITOR
EVENT_NEXT_MONITOR = app_config.NEXT_MONITOR
EVENT_SHUTDOWN_PROMPT = app_config.SHUTDOWN_PROMPT
EVENT_SHUTDOWN = app_config.SHUTDOWN
EVENT_OPEN_GROUP_VIEW = app_config.OPEN_GROUP_VIEW
EVENT_OPEN_MONITOR_LIST_VIEW = 'open_monitor_list_view'

EVENT_MOUSE_CLICK = 'mouse_click'
EVENT_MOUSE_DOWN = 'mouse_down'
EVENT_MOUSE_DRAG = 'mouse_drag'
EVENT_MOUSE_UP = 'mouse_up'

INTERNAL_EVENT_RELEASE_COMPONENT = 'release_component'
INTERNAL_EVENT_HIDE_MOUSE = 'hide_mouse'
INTERNAL_EVENT_SHOW_MOUSE = 'show_mouse'


def get_event_type_configs():
    return [EVENT_QUIT, EVENT_PREV_MONITOR, EVENT_NEXT_MONITOR, EVENT_SHUTDOWN, EVENT_OPEN_GROUP_VIEW,
            EVENT_SHUTDOWN_PROMPT]
